import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "dreamify - visualize your dreams",
    description: "Transform your journal or dream entries into visual stories with panels and narrative generated by AI. Powered by GPT & DALL·E.",
};

export default function RootLayout({
    children,
}:  Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} bg-white text-black dark:bg-[#0e0e0e] dark:text-white transition-colors duration-300`}>
                <div className="min-h-screen flex flex-col">
                <main className="flex-1">{children}</main>
                </div>
            </body>
        </html>
    );
}
